server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # Route for /api/patients/** to patient-service
        ## REST_CLIENT --> http://localhost:4004/api/v1/patients
        ## API-GATEWAY --> http://patient-service:4004/patients
        ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - StripPrefix=0

        # Route for /api/docs/patients to patient-service /v3/api-docs
        ## REST_CLIENT --> http://localhost:4004/api-docs/patients
        ## API-GATEWAY --> http://patient-service:4004/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
